[package]
name        = "flix-fun"
description = "Some util functions implemented in Flix, for fun"
version     = "0.1.0"
flix        = "0.38.0"
authors     = ["An Cao <kcj.pop.com@gmail.com>"]
license     = "MPL-2.0"
