[package]
name        = "99-problems-flix"
description = "99 problems solved in Flix"
version     = "0.1.0"
flix        = "0.38.0"
authors     = ["An Cao <kcj.pop.com@gmail.com>"]
license     = "MPL-2.0"
